# Generated by Django 2.0 on 2019-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Out',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'v_pengeluaran',
                'managed': False,
            },
        ),
    ]
